CREATE DATABASE IF NOT EXISTS `tp1` CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE USER 'tp1'@'localhost' IDENTIFIED BY 'segredo';

CREATE USER 'tp1'@'%' IDENTIFIED BY 'segredo';

GRANT USAGE ON * . * TO 'tp1'@'localhost' IDENTIFIED BY 'segredo' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT USAGE ON * . * TO 'tp1'@'%' IDENTIFIED BY 'segredo' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `tp1` . * TO 'tp1'@'localhost';

GRANT ALL PRIVILEGES ON `tp1` . * TO 'tp1'@'%';